HelloTommy/VIewComponents/NavBarViewComponent.cs
using hiTommy.Data.Services;
using Microsoft.AspNetCore.Mvc;

namespace HelloTommy.Views.Shared.Components
{
    public class NavBarViewComponent : ViewComponent
    {
        public BrandServices _brandServices;


        public NavBarViewComponent(BrandServices brandServices)
        {
            _brandServices = brandServices;
        }

        public IViewComponentResult Invoke()
        {
            var brand = _brandServices.GetAllBrands();
            return View(brand);
        }
    }
}

HelloTommy/Views/Shared/_Layout.cshtml
@using System.Linq;
@using hiTommy.Models;
@{
    
}

@model dynamic
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    @*<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />*@
    @*<link rel="stylesheet" href="~/css/site.css" />*@
    @*<link rel="stylesheet" href="~/css/product-page.css" />*@
    <link rel="stylesheet" href="~/css/style.css" />
    <link rel="stylesheet" href="~/css/header.css" />
    <link rel="stylesheet" href="~/css/navbar.css" />
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat+Subrayada:wght@400;700&family=Roboto+Mono:wght@100&display=swap" rel="stylesheet">
    @RenderSection("Styles", false)

</head>
<body>



    <header>
        <div class="box box-header">
            <a href="/" Home>
                <h1>
                    HiTommy
                </h1>
                <partial name="_LoginPartial" />
            </a>
        </div>
        @await Component.InvokeAsync("NavBar")
    </header>

    <div class="wrapper">
        <main>@RenderBody()</main>

        <footer>
            <div class="footer-container">
                <ul class="footer-items">
                    <li>
                        <a href="/About">About Us</a>
                    </li>
                    <li>
                        <a href="/Contact">Contact</a>
                    </li>
                    <li>
                        <a href="/FAQ">FAQ</a>
                    </li>
                </ul>
            </div>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        <script src="~/lib/jquery-validate/jquery.validate.js"></script>
        <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
    </environment>
    @await RenderSectionAsync("Scripts", false)
</body>
</html>